#!/usr/bin/env sh

DIR="$(cd "$(dirname "$0")" && pwd)"

JAVA_EXEC="${JAVA_HOME:+$JAVA_HOME/bin/}java"
if [ ! -x "$JAVA_EXEC" ]; then
  JAVA_EXEC="java"
fi

exec "$JAVA_EXEC" -Dorg.gradle.appname=gradlew -classpath "$DIR/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"

#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by agent
##
##############################################################################

DIR="$(cd "$(dirname "$0")" && pwd)"

JAVA_EXEC="${JAVA_HOME:+$JAVA_HOME/bin/}java"
if [ ! -x "$JAVA_EXEC" ]; then
  JAVA_EXEC="java"
fi

exec "$JAVA_EXEC" -Dorg.gradle.appname=gradlew -classpath "$DIR/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"

