@rem
@rem Gradle wrapper startup script for Windows
@rem
@echo off
setlocal

set "DIR=%~dp0"

if defined JAVA_HOME (
  set "JAVA_EXE=%JAVA_HOME%\bin\java.exe"
) else (
  if exist "C:\Program Files\Android\Android Studio\jbr\bin\java.exe" (
    set "JAVA_EXE=C:\Program Files\Android\Android Studio\jbr\bin\java.exe"
  ) else (
    set "JAVA_EXE=java"
  )
)

set "JAVA_EXE=%JAVA_EXE:"=%"

"%JAVA_EXE%" -Dorg.gradle.appname=gradlew -classpath "%DIR%gradle\wrapper\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain %*

endlocal

@rem
@rem  Gradle wrapper startup script for Windows generated by agent
@rem
@echo off
setlocal

set "DIR=%~dp0"

if defined JAVA_HOME (
  set "JAVA_EXE=%JAVA_HOME%\bin\java.exe"
) else (
  if exist "C:\Program Files\Android\Android Studio\jbr\bin\java.exe" (
    set "JAVA_EXE=C:\Program Files\Android\Android Studio\jbr\bin\java.exe"
  ) else (
    set "JAVA_EXE=java"
  )
)

set "JAVA_EXE=%JAVA_EXE:"=%"

"%JAVA_EXE%" -Dorg.gradle.appname=gradlew -classpath "%DIR%gradle\wrapper\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain %*

endlocal

