package com.amdevstudio.budgetsense.domain

import java.time.LocalDate

/**
 * Rotating tips — one per calendar day, stable until midnight (device local time).
 * Not personalized; pairs well with data-driven Insights.
 */
object TipsOfTheDay {

    private val tips = listOf(
        "Log expenses the same day you spend — memory fades, but your totals stay honest.",
        "Give every peso (or dollar) a job for needs, wants, savings, or debt. Even a rough split helps.",
        "Before a big purchase, sleep on it once. If it still matters tomorrow, plan how to pay.",
        "Small subscriptions add up. Review recurring charges once a month.",
        "An emergency fund isn’t optional luck — start with one week of expenses, then grow it.",
        "Use Budget caps as guardrails, not guilt. Adjust when life changes.",
        "Naming a savings goal makes it easier to say no to impulse buys.",
        "Compare this month to last in Insights — patterns beat one-off surprises.",
        "Hide balance is for privacy in public; your data on the device is still yours.",
        "Bill reminders work best if notification permission is on — check Android settings.",
        "Income minus expenses isn’t the whole story — track what you actually keep.",
        "If a category keeps blowing the cap, split it (e.g. groceries vs dining out).",
        "Automate what you can off-device; automate tracking here for what you can’t.",
        "Pay future-you first. Even a tiny recurring deposit beats zero.",
        "Weekly check-ins beat monthly panic — open Money for five minutes on Sunday.",
        "Think cash-stuffing in digital form. Caps per category keep spending visible.",
        "Debt snowball or avalanche — pick one and stay consistent; both beat avoidance.",
        "Price per use means dividing cost by how many times you’ll really use something.",
        "Free trials need calendar exits — set a reminder before they bill.",
        "Negotiate bills once a year for internet, insurance, and phone. Silence costs money.",
        "Lifestyle creep is quiet — when income rises, raise savings before spending.",
        "Good enough data beats perfect spreadsheets you never open.",
        "One no-spend weekend a month can reset habits without harsh rules.",
        "Label transactions with notes you’ll understand in six months.",
        "Savings goals with deadlines turn wishes into plans.",
        "If you’re always “left” at zero, lower the cap or raise income — pick one to test.",
        "Insights and tips are rules of thumb. Your numbers tell the real story.",
        "Keep an export or backup mindset. Cloud sync helps when you change phones.",
        "Celebrate milestones — paid a bill early or hit 50% of a goal? That counts.",
        "Boredom is expensive — cheap fun lists beat impulse shopping.",
        "Round up mentally. If something is 990, treat it as 1,000 in your head.",
        "Try two-account thinking with one pile for bills and one for spending. Clarity reduces mistakes.",
        "Review Savings rings on Home — progress you can see stays motivating.",
        "Money arguments shrink when the numbers are shared — show the app, not blame.",
        "Inflation hits fixed incomes harder — revisit your monthly total quarterly.",
        "Sleep, food, and stability first — optimize investments after basics are solid.",
        "Set a monthly spending limit to avoid overspending.",
        "Track every expense, even small purchases.",
        "Create separate budgets for needs and wants.",
        "Review your budget weekly to stay on track.",
        "Avoid impulse buying by waiting 24 hours before purchasing.",
        "Use the 50/30/20 budgeting rule.",
        "Always budget for emergencies.",
        "Plan your expenses before payday.",
        "Stick to your grocery list when shopping.",
        "Set realistic financial goals.",
        "Save at least 10% of your income every month.",
        "Start building an emergency fund today.",
        "Small savings add up over time.",
        "Automate your savings whenever possible.",
        "Set savings goals with deadlines.",
        "Avoid spending your extra income immediately.",
        "Save coins and spare cash regularly.",
        "Reduce unnecessary subscriptions.",
        "Save before spending, not after.",
        "Celebrate small savings milestones.",
        "Categorize expenses to understand spending habits.",
        "Monitor your highest expense category monthly.",
        "Compare this month’s expenses with last month’s.",
        "Review your daily expenses every evening.",
        "Record expenses immediately after spending.",
        "Identify spending patterns to improve budgeting.",
        "Keep your expense entries consistent.",
        "Use charts and analytics to understand your finances.",
        "Don’t ignore small recurring expenses.",
        "Track cash expenses too.",
        "Needs come before wants.",
        "Financial discipline builds long-term stability.",
        "Avoid emotional spending.",
        "Paying with cash can reduce overspending.",
        "Always compare prices before buying.",
        "Learn to distinguish luxuries from necessities.",
        "A budget gives you control over your money.",
        "Financial habits matter more than income size.",
        "Consistency is the key to financial growth.",
        "Saving money is a form of self-care.",
        "Use savings goals to stay motivated.",
        "Check your insights regularly for smarter spending.",
        "Sync your account to keep data across devices.",
        "You can use BudgetSense offline anytime.",
        "Add categories to better organize expenses.",
        "Use charts to visualize your spending habits.",
        "Keep your app updated for new features.",
        "Review your monthly analytics for better planning.",
        "Currency converter helps track foreign spending.",
        "Backup your data by signing in with Google.",
        "Every peso saved matters.",
        "Financial freedom starts with small habits.",
        "Smart spending leads to smarter living.",
        "Progress is progress, no matter how small.",
        "Your future self will thank you for saving today.",
        "Building wealth takes patience and discipline.",
        "A good budget creates peace of mind.",
        "Spending wisely is a superpower.",
        "Saving money is investing in your future.",
        "Start today, not next month.",
        "Separate emergency funds from savings goals.",
        "Track recurring expenses separately.",
        "Review subscriptions every 3 months.",
        "Use weekly spending limits for better control.",
        "Avoid lifestyle inflation after salary increases.",
        "Prioritize paying high-interest debt first.",
        "Budget for annual expenses monthly.",
        "Monitor spending trends using analytics.",
        "Set short-term and long-term financial goals.",
        "Build a habit of reviewing finances every Sunday.",
    )

    fun forToday(): String = forDate(LocalDate.now())

    fun forDate(date: LocalDate): String {
        if (tips.isEmpty()) return ""
        val n = tips.size.toLong()
        val ed = date.toEpochDay()
        val idx = ((ed % n) + n) % n
        return tips[idx.toInt()]
    }
}
